// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pspmhtufdhkdpqgpefgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcG1odHVmZGhrZHBxZ3BlZmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjQ1MDMsImV4cCI6MjA2Mzk0MDUwM30.C-Q8v7kaiY5G4l13mr_DS6T0kyhPQO5SKvH3IYFI5Bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);